pipeline:
  stages:
    - stage:
        name: automated test
        steps:
        - script: 
              mvn clean test -DsuiteFile='src/test/resources/test-suites/CucumberRunner.xml' -DgridHub='http://localhost:4444'

    - stage:
        name: publish report
        steps:
          - script:
              allure generate --clean

  # post:
  #   always:
  #     - archiveArtifacts:
  #         artifacts: 'allure-results/**/*'

  #     - publishHTML:
  #         target:
  #           allowMissing: false
  #           alwaysLinkToLastBuild: true
  #           keepAll: true
  #           reportDir: 'allure-report'
  #           reportFiles: 'index.html'
  #           reportName: 'allure-report'
  #           reportTitles: ''
  #           useWrapperFileDirectly: true

  #     - script:
  #       - // Get hashed build ID after test finished
  #         def buildID = readFile 'build_hashed_id.txt'
  #       - def blocks = [
  #           [
  #             "type": "header",
  #             "text": [
  #               "type": "plain_text",
  #               "text": "FINISHED TEST"
  #             ]
  #           ],
  #           [
  #             "type": "divider"
  #           ],
  #           [
  #             "type": "section",
  #             "text": [
  #               "type": "mrkdwn",
  #               "text": ":sunny: Job *${env.JOB_NAME}*'s result is ${currentBuild.currentResult}.\n*Summary:*"
  #             ]
  #           ],
  #           [
  #             "type": "section",
  #             "text": [
  #               "type": "mrkdwn",
  #               "text": "`${result}`"
  #             ]
  #           ],
  #           [
  #             "type": "divider"
  #           ],
  #           [
  #             "type": "section",
  #             "text": [
  #               "type": "mrkdwn",
  #               "text": ":pushpin: More info at:\n• *Build URL:* ${env.BUILD_URL}console\n• *Allure Report:* ${env.BUILD_URL}allure-report\n• *BrowserStack build URL:* https://automate.browserstack.com/dashboard/v2/builds/${buildID}"
  #             ]
  #           ],
  #         ]

  #       - // Send notification
  #         slackSend channel: 'automation-test-notifications', blocks: blocks, teamDomain: 'agileops', tokenCredentialId: 'jenkins-slack', botUser: true
