# CircleCI configuration file
version: 2.1
general:
  branches:
    only: dev
# setup: true
orbs:
  browser-tools: circleci/browser-tools@1.4.1

################################# ANCHORS #################################
# Define the commands we want to use in our jobs
install_dependencies: &install_dependencies
  run:
    name: Install dependencies
    command: |
      sudo apt update -y
      sudo apt-get install openjdk-8-jdk -y
      sudo apt autoremove -y
      wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure_2.21.0-1_all.deb
      sudo dpkg -i allure_*
      sudo apt-get install -f
      wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.8.0/selenium-server-4.8.2.jar
      wget http://www.java2s.com/Code/JarDownload/testng/testng-6.8.7.jar.zip
      unzip testng-6.8.7.jar.zip
      sudo ln -s /usr/local/bin/chromedriver ~/project/chromedriver

selenium_server_start: &selenium_server_start
  run:
    name: Start selenium server
    command: xvfb-run java -Dwebdriver.gecko.driver=geckodriver -Dwebdriver.chrome.driver=chromedriver -jar selenium-server-4.8.2.jar standalone
    background: true

############################# JOBS ########################################
# Define the jobs we want to run for this project
jobs:
  test:
    docker:
      - image: cimg/openjdk:11.0.18-browsers
      
    # Run test in parallel
    parallelism: 2
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - browser-tools/install-browser-tools:
          chrome-version: 111.0.5563.147
          firefox-version: 111.0.1

      - run:
          command: |
            google-chrome --version
            firefox --version
            geckodriver --version
            chromedriver --version
            java -jar /usr/local/bin/selenium.jar --version
            pkill Xvfb
          name: Check installed versions
      
      - *install_dependencies
      - *selenium_server_start

      - run:
          name: Run tests
          command: |
            unset DISPLAY
            circleci tests glob "src/test/java/runner/*.java" | circleci tests split
            mvn clean test -DsuiteFile=src/test/resources/test-suites/CucumberRunner.xml -DgridHub=http://localhost:4444
            allure generate --clean

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - store_test_results:
          path: allure-results
      - store_artifacts:
          path: allure-report
          destination: allure-report

################################ WORKFLOWS ################################
# Orchestrate our job run sequence
workflows:
  selenium-tests:
    jobs:
      - test