# CircleCI configuration file
version: 2.1
general:
  branches:
    only: dev
# setup: true
orbs:
  browser-tools: circleci/browser-tools@1.4.1

# Define the jobs we want to run for this project
jobs:
  setup:
    docker:
      - image: cimg/openjdk:11.0.18-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: 111.0.5563.147
          chromedriver-install-dir: ~/project/chromedriver
          firefox-version: 111.0.1
          # geckodriver-install-dir: ~/project/geckodriver
      - run:
          command: |
            google-chrome --version
            firefox --version
            geckodriver --version
            chromedriver --version
            java -jar /usr/local/bin/selenium.jar --version
          name: Check install
      - run:
          name: Install dependencies
          command: |
            sudo apt update -y
            sudo apt-get install openjdk-8-jdk -y
            sudo apt autoremove -y
            wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure_2.21.0-1_all.deb
            sudo dpkg -i allure_*
            sudo apt-get install -f
            wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.8.0/selenium-server-4.8.2.jar
            wget http://www.java2s.com/Code/JarDownload/testng/testng-6.8.7.jar.zip
            unzip testng-6.8.7.jar.zip
  
  start_selenium:
    docker:
      - image: cimg/openjdk:11.0.18-browsers
    steps:
      - run:
          name: Start Selenium
          command: |
            pkill Xvfb
            xvfb-run java -Dwebdriver.gecko.driver=geckodriver -Dwebdriver.chrome.driver=chromedriver -jar selenium-server-4.8.2.jar standalone
          # background: true
  test:
    docker:
      - image: cimg/openjdk:11.0.18-browsers
    steps:
      - run:
          name: Run tests
          command: |
            mvn clean test -DsuiteFile=src/test/resources/test-suites/CucumberRunner.xml -DgridHub=http://localhost:4444
            allure generate --clean

# Orchestrate our job run sequence
workflows:
  test:
    jobs:
      - setup
      - start_selenium:
          requires:
            - setup
      - test