name: trigger jenkins job
on:
  push:
    branches:
    - dev
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger jenkins job
      uses: jabbukka/jenkins-trigger@main
      with:
        url: ${{ secrets.JENKINS_URL }}
        job_name: "selenium"
        user_name: admin
        api_token: ${{ secrets.JENKINS_TOKEN }}
        wait: "true"
        timeout: "5000"